"""add cooling_capacity_w

Revision ID: 0ec8237be6d7
Revises: fb9b7245773e
Create Date: 2026-06-10 16:56:43.067549

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0ec8237be6d7"
down_revision: Union[str, Sequence[str], None] = "fb9b7245773e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "racks",
        sa.Column(
            "cooling_capacity_w", sa.DECIMAL(precision=10, scale=2), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("racks", "cooling_capacity_w")
    # ### end Alembic commands ###
