"""add_power_domain_tables_and_vde_fields

Revision ID: 1f7296a624f3
Revises: ba4f7fa027b8
Create Date: 2026-05-27 11:40:20.348564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f7296a624f3'
down_revision: Union[str, Sequence[str], None] = 'ba4f7fa027b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distribution_panels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bezeichnung', sa.String(length=100), nullable=False),
    sa.Column('rack_id', sa.Integer(), nullable=True),
    sa.Column('usv_unit_id', sa.Integer(), nullable=True),
    sa.Column('bemerkung', sa.String(length=255), nullable=True),
    sa.Column('has_epo_contact', sa.Boolean(), nullable=False),
    sa.Column('redundancy_path', sa.Enum('A', 'B'), nullable=True),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usv_unit_id'], ['usv_units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usv_calculations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('berechnet_am', sa.DateTime(), nullable=False),
    sa.Column('usv_unit_id', sa.Integer(), nullable=False),
    sa.Column('last_kw', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('peak_kw', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('installiert_kw', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('reserve_kw', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('n1_kw', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('kaltstart_ok', sa.Boolean(), nullable=False),
    sa.Column('bemerkung', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['usv_unit_id'], ['usv_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distribution_circuits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('bezeichnung', sa.String(length=50), nullable=False),
    sa.Column('phase', sa.Enum('L1', 'L2', 'L3'), nullable=False),
    sa.Column('absicherung_a', sa.DECIMAL(precision=5, scale=1), nullable=False),
    sa.Column('max_watt', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['panel_id'], ['distribution_panels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('usv_units', sa.Column('battery_strings', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('usv_units', sa.Column('has_bypass_switch', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('usv_units', sa.Column('redundancy_path', sa.Enum('A', 'B'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usv_units', 'redundancy_path')
    op.drop_column('usv_units', 'has_bypass_switch')
    op.drop_column('usv_units', 'battery_strings')
    op.drop_table('distribution_circuits')
    op.drop_table('usv_calculations')
    op.drop_table('distribution_panels')
    # ### end Alembic commands ###
