"""feat: add IPAM models

Revision ID: 2464a98fc0e9
Revises: 162f02320fa0
Create Date: 2026-05-25 17:46:35.586361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2464a98fc0e9'
down_revision: Union[str, Sequence[str], None] = '162f02320fa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vlans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vlan_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('bemerkung', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vlan_id')
    )
    op.create_table('subnets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('network', sa.String(length=45), nullable=False),
    sa.Column('gateway', sa.String(length=45), nullable=True),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vlan_id'], ['vlans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network')
    )
    op.add_column('devices', sa.Column('subnet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'devices', 'subnets', ['subnet_id'], ['id'], ondelete='SET NULL')
    op.add_column('virtual_machines', sa.Column('subnet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'virtual_machines', 'subnets', ['subnet_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'virtual_machines', type_='foreignkey')
    op.drop_column('virtual_machines', 'subnet_id')
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_column('devices', 'subnet_id')
    op.drop_table('subnets')
    op.drop_table('vlans')
    # ### end Alembic commands ###
