"""add battery string fields to usv_units

Revision ID: 359168ea3c12
Revises: 47148cf138dd
Create Date: 2026-05-29 23:06:07.383829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '359168ea3c12'
down_revision: Union[str, Sequence[str], None] = '47148cf138dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usv_units', sa.Column('blocks_per_string', sa.Integer(), nullable=False, server_default='32'))
    op.add_column('usv_units', sa.Column('block_voltage_v', sa.DECIMAL(precision=5, scale=2), nullable=False, server_default='12.00'))
    op.add_column('usv_units', sa.Column('block_capacity_ah', sa.DECIMAL(precision=7, scale=2), nullable=False, server_default='100.00'))
    op.alter_column('usv_units', 'battery_strings', server_default='2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usv_units', 'battery_strings', server_default='1')
    op.drop_column('usv_units', 'block_capacity_ah')
    op.drop_column('usv_units', 'block_voltage_v')
    op.drop_column('usv_units', 'blocks_per_string')
    # ### end Alembic commands ###
