"""add_device_shutdown_fields

Revision ID: 44396c87d2a5
Revises: 3e4f5a6b7c8d
Create Date: 2026-05-22 20:58:30.814811

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "44396c87d2a5"
down_revision: Union[str, Sequence[str], None] = "3e4f5a6b7c8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    # Drop foreign key constraint on devices first so distribution_circuits can be dropped
    try:
        op.drop_constraint("devices_ibfk_2", "devices", type_="foreignkey")
    except Exception:
        pass

    # Clean up interfaces if it exists from a previous partial run
    if "interfaces" in tables:
        # Drop foreign keys on cable_strands pointing to interfaces if they were created
        try:
            op.drop_constraint(
                "cable_strands_ibfk_3", "cable_strands", type_="foreignkey"
            )
        except Exception:
            pass
        try:
            op.drop_constraint(
                "cable_strands_ibfk_2", "cable_strands", type_="foreignkey"
            )
        except Exception:
            pass
        op.drop_table("interfaces")

    op.create_table(
        "interfaces",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("port_name", sa.String(length=50), nullable=False),
        sa.Column("typ", sa.String(length=50), nullable=False),
        sa.Column("mac_adresse", sa.String(length=17), nullable=True),
        sa.Column("status", sa.Enum("frei", "belegt", "defekt"), nullable=False),
        sa.Column("kabel_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["kabel_id"], ["cables.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )

    # Data migration: Copy existing device_ports to interfaces, keeping the IDs so cable_strands relations remain intact
    if "device_ports" in tables:
        op.execute(
            "INSERT INTO interfaces (id, device_id, port_name, typ, mac_adresse, status, kabel_id) "
            "SELECT id, device_id, port_name, typ, NULL, status, kabel_id FROM device_ports"
        )
    # Data migration: Copy server_interfaces to interfaces, letting auto-increment handle new IDs
    if "server_interfaces" in tables:
        op.execute(
            "INSERT INTO interfaces (device_id, port_name, typ, mac_adresse, status, kabel_id) "
            "SELECT device_id, port_name, typ, mac_adresse, "
            "CASE WHEN kabel_id IS NOT NULL THEN 'belegt' ELSE 'frei' END, kabel_id FROM server_interfaces"
        )

    try:
        op.drop_constraint("cable_strands_ibfk_3", "cable_strands", type_="foreignkey")
    except Exception:
        pass
    try:
        op.drop_constraint("cable_strands_ibfk_2", "cable_strands", type_="foreignkey")
    except Exception:
        pass

    if "device_ports" in tables:
        op.drop_table("device_ports")
    if "server_interfaces" in tables:
        op.drop_table("server_interfaces")
    if "distribution_circuits" in tables:
        op.drop_table("distribution_circuits")
    if "usv_calculations" in tables:
        op.drop_table("usv_calculations")
    if "distribution_panels" in tables:
        op.drop_table("distribution_panels")
    if "kentix_readings" in tables:
        op.drop_table("kentix_readings")

    try:
        op.create_foreign_key(
            None,
            "cable_strands",
            "interfaces",
            ["von_port_id"],
            ["id"],
            ondelete="SET NULL",
        )
    except Exception:
        pass
    try:
        op.create_foreign_key(
            None,
            "cable_strands",
            "interfaces",
            ["nach_port_id"],
            ["id"],
            ondelete="SET NULL",
        )
    except Exception:
        pass

    device_columns = [col["name"] for col in inspector.get_columns("devices")]
    if "shutdown_delay_seconds" not in device_columns:
        op.add_column(
            "devices", sa.Column("shutdown_delay_seconds", sa.Integer(), nullable=True)
        )
    if "shutdown_priority" not in device_columns:
        op.add_column(
            "devices", sa.Column("shutdown_priority", sa.Integer(), nullable=True)
        )

    if "api_url" in device_columns:
        op.drop_column("devices", "api_url")
    if "circuit_id" in device_columns:
        op.drop_column("devices", "circuit_id")
    if "api_key" in device_columns:
        op.drop_column("devices", "api_key")

    op.alter_column(
        "racks",
        "breite_mm",
        existing_type=mysql.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("'600'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "racks",
        "breite_mm",
        existing_type=mysql.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("'600'"),
    )
    op.add_column(
        "devices", sa.Column("api_key", mysql.VARCHAR(length=255), nullable=True)
    )
    op.add_column(
        "devices",
        sa.Column("circuit_id", mysql.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "devices", sa.Column("api_url", mysql.VARCHAR(length=255), nullable=True)
    )
    op.create_foreign_key(
        op.f("devices_ibfk_2"),
        "devices",
        "distribution_circuits",
        ["circuit_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("devices", "shutdown_priority")
    op.drop_column("devices", "shutdown_delay_seconds")
    op.drop_constraint(None, "cable_strands", type_="foreignkey")
    op.drop_constraint(None, "cable_strands", type_="foreignkey")
    op.create_foreign_key(
        op.f("cable_strands_ibfk_2"),
        "cable_strands",
        "device_ports",
        ["nach_port_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("cable_strands_ibfk_3"),
        "cable_strands",
        "device_ports",
        ["von_port_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_table(
        "kentix_readings",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("device_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("gemessen_am", mysql.DATETIME(), nullable=False),
        sa.Column("temperatur_c", mysql.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column(
            "luftfeuchte_pct", mysql.DECIMAL(precision=5, scale=2), nullable=True
        ),
        sa.Column(
            "alarm_aktiv",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("alarm_typ", mysql.VARCHAR(length=100), nullable=True),
        sa.Column("raw_json", mysql.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("kentix_readings_ibfk_1"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "distribution_panels",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("bezeichnung", mysql.VARCHAR(length=100), nullable=False),
        sa.Column("rack_id", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("usv_unit_id", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("bemerkung", mysql.VARCHAR(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["rack_id"],
            ["racks.id"],
            name=op.f("distribution_panels_ibfk_1"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["usv_unit_id"],
            ["usv_units.id"],
            name=op.f("distribution_panels_ibfk_2"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "usv_calculations",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("berechnet_am", mysql.DATETIME(), nullable=False),
        sa.Column("usv_unit_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("last_kw", mysql.DECIMAL(precision=8, scale=2), nullable=False),
        sa.Column("peak_kw", mysql.DECIMAL(precision=8, scale=2), nullable=False),
        sa.Column(
            "installiert_kw", mysql.DECIMAL(precision=8, scale=2), nullable=False
        ),
        sa.Column("reserve_kw", mysql.DECIMAL(precision=8, scale=2), nullable=False),
        sa.Column("n1_kw", mysql.DECIMAL(precision=8, scale=2), nullable=False),
        sa.Column(
            "kaltstart_ok",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("bemerkung", mysql.VARCHAR(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["usv_unit_id"],
            ["usv_units.id"],
            name=op.f("usv_calculations_ibfk_1"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "distribution_circuits",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("panel_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("bezeichnung", mysql.VARCHAR(length=50), nullable=False),
        sa.Column("phase", mysql.ENUM("L1", "L2", "L3", "L1+L2+L3"), nullable=False),
        sa.Column("absicherung_a", mysql.DECIMAL(precision=5, scale=1), nullable=False),
        sa.Column("max_watt", mysql.DECIMAL(precision=8, scale=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["panel_id"],
            ["distribution_panels.id"],
            name=op.f("distribution_circuits_ibfk_1"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "server_interfaces",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("device_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("port_name", mysql.VARCHAR(length=50), nullable=False),
        sa.Column(
            "typ",
            mysql.ENUM(
                "1GbE", "10GbE", "25GbE", "40GbE", "100GbE", "FC", "IPMI", "sonstige"
            ),
            nullable=False,
        ),
        sa.Column("mac_adresse", mysql.VARCHAR(length=17), nullable=True),
        sa.Column("switch_hostname", mysql.VARCHAR(length=100), nullable=True),
        sa.Column("switch_port", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("kabel_id", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("server_interfaces_ibfk_3"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["kabel_id"],
            ["cables.id"],
            name=op.f("server_interfaces_ibfk_2"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "device_ports",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("device_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("port_name", mysql.VARCHAR(length=50), nullable=False),
        sa.Column("typ", mysql.VARCHAR(length=50), nullable=False),
        sa.Column("status", mysql.ENUM("frei", "belegt", "defekt"), nullable=False),
        sa.Column("kabel_id", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("device_ports_ibfk_3"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["kabel_id"],
            ["cables.id"],
            name=op.f("device_ports_ibfk_2"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("interfaces")
    # ### end Alembic commands ###
