"""add_device_dependencies_and_shutdown_method

Revision ID: 582ca8d0a3bf
Revises: d02c996b4cfd
Create Date: 2026-05-25 02:00:16.432343

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "582ca8d0a3bf"
down_revision: Union[str, Sequence[str], None] = "d02c996b4cfd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_dependencies",
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("depends_on_device_id", sa.Integer(), nullable=False),
        sa.Column("dependency_type", sa.String(length=50), nullable=True),
        sa.Column("dependency_group", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["depends_on_device_id"], ["devices.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("device_id", "depends_on_device_id"),
    )
    op.add_column(
        "devices",
        sa.Column(
            "shutdown_method",
            sa.Enum("ACPI_Graceful", "SSH_Script", "Hard_Power_Cut_PDU"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("devices", "shutdown_method")
    op.drop_table("device_dependencies")
    # ### end Alembic commands ###
