"""add rackreihe to racks

Revision ID: 63c61f2b3e3a
Revises: 2464a98fc0e9
Create Date: 2026-05-25 18:54:01.087023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63c61f2b3e3a'
down_revision: Union[str, Sequence[str], None] = '2464a98fc0e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('racks', sa.Column('rackreihe', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('racks', 'rackreihe')
    # ### end Alembic commands ###
