"""add ipv6_adresse to device and vm

Revision ID: 6f387c8453df
Revises: 0ec8237be6d7
Create Date: 2026-06-11 22:15:01.605927

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6f387c8453df"
down_revision: Union[str, Sequence[str], None] = "0ec8237be6d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devices", sa.Column("ipv6_adresse", sa.String(length=45), nullable=True)
    )
    op.add_column(
        "virtual_machines",
        sa.Column("ipv6_adresse", sa.String(length=45), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("virtual_machines", "ipv6_adresse")
    op.drop_column("devices", "ipv6_adresse")
    # ### end Alembic commands ###
