"""add rackreihe

Revision ID: 85ed2c02ef79
Revises: 63c61f2b3e3a
Create Date: 2026-05-26 23:42:53.878302

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "85ed2c02ef79"
down_revision: Union[str, Sequence[str], None] = "63c61f2b3e3a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "racks", sa.Column("max_watt", sa.DECIMAL(precision=10, scale=2), nullable=True)
    )
    op.add_column("racks", sa.Column("usv_n1_redundant", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("racks", "usv_n1_redundant")
    op.drop_column("racks", "max_watt")
    # ### end Alembic commands ###
