"""add geaendert_von to power models

Revision ID: 916cf0460469
Revises: 265b942f7bd2
Create Date: 2026-05-31 15:37:21.640264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '916cf0460469'
down_revision: Union[str, Sequence[str], None] = '265b942f7bd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distribution_panels', sa.Column('geaendert_von', sa.String(length=100), nullable=True))
    op.add_column('usv_modules', sa.Column('geaendert_von', sa.String(length=100), nullable=True))
    op.add_column('usv_units', sa.Column('geaendert_von', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usv_units', 'geaendert_von')
    op.drop_column('usv_modules', 'geaendert_von')
    op.drop_column('distribution_panels', 'geaendert_von')
    # ### end Alembic commands ###
