"""cascade_delete_constraints_v2

Revision ID: b346b3c9139b
Revises: bb2406ada639
Create Date: 2026-05-21 22:49:36.054242

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b346b3c9139b"
down_revision: Union[str, Sequence[str], None] = "bb2406ada639"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("cable_strands_ibfk_1"), "cable_strands", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "cable_strands", "cables", ["cable_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("device_ports_ibfk_1"), "device_ports", type_="foreignkey")
    op.create_foreign_key(
        None, "device_ports", "devices", ["device_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("devices_ibfk_2"), "devices", type_="foreignkey")
    op.drop_constraint(op.f("devices_ibfk_1"), "devices", type_="foreignkey")
    op.create_foreign_key(
        None, "devices", "racks", ["rack_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "devices",
        "distribution_circuits",
        ["circuit_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(
        op.f("distribution_circuits_ibfk_1"),
        "distribution_circuits",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "distribution_circuits",
        "distribution_panels",
        ["panel_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("distribution_panels_ibfk_1"), "distribution_panels", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("distribution_panels_ibfk_2"), "distribution_panels", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "distribution_panels", "racks", ["rack_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "distribution_panels",
        "usv_units",
        ["usv_unit_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(
        op.f("kentix_readings_ibfk_1"), "kentix_readings", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "kentix_readings", "devices", ["device_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("pdu_outlets_ibfk_1"), "pdu_outlets", type_="foreignkey")
    op.create_foreign_key(
        None, "pdu_outlets", "devices", ["pdu_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("server_interfaces_ibfk_1"), "server_interfaces", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "server_interfaces", "devices", ["device_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("usv_calculations_ibfk_1"), "usv_calculations", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "usv_calculations",
        "usv_units",
        ["usv_unit_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("usv_modules_ibfk_1"), "usv_modules", type_="foreignkey")
    op.create_foreign_key(
        None, "usv_modules", "usv_units", ["usv_unit_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("usv_simulation_events_ibfk_1"),
        "usv_simulation_events",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "usv_simulation_events",
        "usv_units",
        ["usv_unit_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("usv_units_ibfk_1"), "usv_units", type_="foreignkey")
    op.create_foreign_key(
        None, "usv_units", "racks", ["rack_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "usv_units", type_="foreignkey")
    op.create_foreign_key(
        op.f("usv_units_ibfk_1"), "usv_units", "racks", ["rack_id"], ["id"]
    )
    op.drop_constraint(None, "usv_simulation_events", type_="foreignkey")
    op.create_foreign_key(
        op.f("usv_simulation_events_ibfk_1"),
        "usv_simulation_events",
        "usv_units",
        ["usv_unit_id"],
        ["id"],
    )
    op.drop_constraint(None, "usv_modules", type_="foreignkey")
    op.create_foreign_key(
        op.f("usv_modules_ibfk_1"), "usv_modules", "usv_units", ["usv_unit_id"], ["id"]
    )
    op.drop_constraint(None, "usv_calculations", type_="foreignkey")
    op.create_foreign_key(
        op.f("usv_calculations_ibfk_1"),
        "usv_calculations",
        "usv_units",
        ["usv_unit_id"],
        ["id"],
    )
    op.drop_constraint(None, "server_interfaces", type_="foreignkey")
    op.create_foreign_key(
        op.f("server_interfaces_ibfk_1"),
        "server_interfaces",
        "devices",
        ["device_id"],
        ["id"],
    )
    op.drop_constraint(None, "pdu_outlets", type_="foreignkey")
    op.create_foreign_key(
        op.f("pdu_outlets_ibfk_1"), "pdu_outlets", "devices", ["pdu_id"], ["id"]
    )
    op.drop_constraint(None, "kentix_readings", type_="foreignkey")
    op.create_foreign_key(
        op.f("kentix_readings_ibfk_1"),
        "kentix_readings",
        "devices",
        ["device_id"],
        ["id"],
    )
    op.drop_constraint(None, "distribution_panels", type_="foreignkey")
    op.drop_constraint(None, "distribution_panels", type_="foreignkey")
    op.create_foreign_key(
        op.f("distribution_panels_ibfk_2"),
        "distribution_panels",
        "usv_units",
        ["usv_unit_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("distribution_panels_ibfk_1"),
        "distribution_panels",
        "racks",
        ["rack_id"],
        ["id"],
    )
    op.drop_constraint(None, "distribution_circuits", type_="foreignkey")
    op.create_foreign_key(
        op.f("distribution_circuits_ibfk_1"),
        "distribution_circuits",
        "distribution_panels",
        ["panel_id"],
        ["id"],
    )
    op.drop_constraint(None, "devices", type_="foreignkey")
    op.drop_constraint(None, "devices", type_="foreignkey")
    op.create_foreign_key(
        op.f("devices_ibfk_1"), "devices", "racks", ["rack_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("devices_ibfk_2"),
        "devices",
        "distribution_circuits",
        ["circuit_id"],
        ["id"],
    )
    op.drop_constraint(None, "device_ports", type_="foreignkey")
    op.create_foreign_key(
        op.f("device_ports_ibfk_1"), "device_ports", "devices", ["device_id"], ["id"]
    )
    # op.drop_constraint(None, "cable_strands", type_="foreignkey")
    op.create_foreign_key(
        op.f("cable_strands_ibfk_1"), "cable_strands", "cables", ["cable_id"], ["id"]
    )
    # ### end Alembic commands ###
