"""cascade_delete_rules

Revision ID: bb2406ada639
Revises:
Create Date: 2026-05-21 22:45:08.765145

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "bb2406ada639"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("cable_strands_ibfk_3"), "cable_strands", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("cable_strands_ibfk_2"), "cable_strands", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "cable_strands",
        "device_ports",
        ["nach_port_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None,
        "cable_strands",
        "device_ports",
        ["von_port_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(op.f("cables_ibfk_1"), "cables", type_="foreignkey")
    op.drop_constraint(op.f("cables_ibfk_2"), "cables", type_="foreignkey")
    op.create_foreign_key(
        None, "cables", "devices", ["nach_device_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "cables", "devices", ["von_device_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_constraint(op.f("device_ports_ibfk_2"), "device_ports", type_="foreignkey")
    op.create_foreign_key(
        None, "device_ports", "cables", ["kabel_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_constraint(op.f("pdu_outlets_ibfk_2"), "pdu_outlets", type_="foreignkey")
    op.create_foreign_key(
        None,
        "pdu_outlets",
        "devices",
        ["connected_device_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(
        op.f("server_interfaces_ibfk_2"), "server_interfaces", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "server_interfaces", "cables", ["kabel_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "server_interfaces", type_="foreignkey")
    op.create_foreign_key(
        op.f("server_interfaces_ibfk_2"),
        "server_interfaces",
        "cables",
        ["kabel_id"],
        ["id"],
    )
    op.drop_constraint(None, "pdu_outlets", type_="foreignkey")
    op.create_foreign_key(
        op.f("pdu_outlets_ibfk_2"),
        "pdu_outlets",
        "devices",
        ["connected_device_id"],
        ["id"],
    )
    op.drop_constraint(None, "device_ports", type_="foreignkey")
    op.create_foreign_key(
        op.f("device_ports_ibfk_2"), "device_ports", "cables", ["kabel_id"], ["id"]
    )
    op.drop_constraint(None, "cables", type_="foreignkey")
    op.drop_constraint(None, "cables", type_="foreignkey")
    op.create_foreign_key(
        op.f("cables_ibfk_2"), "cables", "devices", ["nach_device_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("cables_ibfk_1"), "cables", "devices", ["von_device_id"], ["id"]
    )
    # op.drop_constraint(None, "cable_strands", type_="foreignkey")
    # op.drop_constraint(None, "cable_strands", type_="foreignkey")
    op.create_foreign_key(
        op.f("cable_strands_ibfk_2"),
        "cable_strands",
        "device_ports",
        ["von_port_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("cable_strands_ibfk_3"),
        "cable_strands",
        "device_ports",
        ["nach_port_id"],
        ["id"],
    )
    # ### end Alembic commands ###
