"""initial sqlite baseline

Revision ID: ca6d87134691
Revises: 
Create Date: 2026-06-23 08:24:09.005000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca6d87134691'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('racks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('standort', sa.String(length=100), nullable=False),
    sa.Column('rackreihe', sa.String(length=100), nullable=True),
    sa.Column('hoehe_u', sa.Integer(), nullable=False),
    sa.Column('breite_mm', sa.Integer(), nullable=True),
    sa.Column('bemerkung', sa.String(length=255), nullable=True),
    sa.Column('hersteller', sa.String(length=100), nullable=True),
    sa.Column('modell', sa.String(length=100), nullable=True),
    sa.Column('hardware_type_id', sa.Integer(), nullable=True),
    sa.Column('max_watt', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('cooling_capacity_w', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('usv_n1_redundant', sa.Boolean(), nullable=False),
    sa.Column('geaendert_von', sa.String(length=100), nullable=True),
    sa.Column('geaendert_am', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('runbooks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('typ', sa.Enum('shutdown', 'startup', 'wartung', 'notfall', 'custom'), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=False),
    sa.Column('erstellt_von', sa.String(length=100), nullable=True),
    sa.Column('generated_from_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['generated_from_id'], ['runbooks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vlans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vlan_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('bemerkung', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vlan_id')
    )
    op.create_table('runbook_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('runbook_id', sa.Integer(), nullable=False),
    sa.Column('gestartet_am', sa.DateTime(), nullable=False),
    sa.Column('gestartet_von', sa.String(length=100), nullable=True),
    sa.Column('modus', sa.Enum('shutdown', 'startup'), nullable=False),
    sa.Column('status', sa.Enum('offen', 'abgeschlossen', 'verworfen'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['runbook_id'], ['runbooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runbook_layers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('runbook_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('markdown_note', sa.Text(), nullable=True),
    sa.Column('shutdown_order', sa.Integer(), nullable=True),
    sa.Column('startup_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['runbook_id'], ['runbooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subnets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('network', sa.String(length=45), nullable=False),
    sa.Column('gateway', sa.String(length=45), nullable=True),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vlan_id'], ['vlans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network')
    )
    op.create_table('usv_units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bezeichnung', sa.String(length=100), nullable=False),
    sa.Column('hersteller', sa.String(length=100), nullable=False),
    sa.Column('rack_id', sa.Integer(), nullable=False),
    sa.Column('max_kw', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('battery_strings', sa.Integer(), nullable=False),
    sa.Column('blocks_per_string', sa.Integer(), nullable=False),
    sa.Column('block_voltage_v', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('block_capacity_ah', sa.DECIMAL(precision=7, scale=2), nullable=False),
    sa.Column('has_bypass_switch', sa.Boolean(), nullable=False),
    sa.Column('redundancy_path', sa.Enum('A', 'B'), nullable=True),
    sa.Column('geaendert_von', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('typ', sa.Enum('server', 'switch', 'pdu', 'storage', 'firewall', 'kentix_raconode', 'kentix_doormaster', 'kentix_multisensor', 'usv', 'patchpanel', 'sonstige'), nullable=False),
    sa.Column('hostname', sa.String(length=100), nullable=False),
    sa.Column('ip_adresse', sa.String(length=45), nullable=True),
    sa.Column('ipv6_adresse', sa.String(length=45), nullable=True),
    sa.Column('hersteller', sa.String(length=100), nullable=True),
    sa.Column('modell', sa.String(length=100), nullable=True),
    sa.Column('seriennummer', sa.String(length=100), nullable=True),
    sa.Column('rack_id', sa.Integer(), nullable=True),
    sa.Column('u_position', sa.Integer(), nullable=True),
    sa.Column('u_hoehe', sa.Integer(), nullable=False),
    sa.Column('side', sa.Enum('left', 'right'), nullable=True),
    sa.Column('subnet_id', sa.Integer(), nullable=True),
    sa.Column('phase', sa.Enum('L1', 'L2', 'L3'), nullable=True),
    sa.Column('tdp_watt', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('psu_count', sa.Integer(), nullable=True),
    sa.Column('psu_nennwatt', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('last_pct', sa.DECIMAL(precision=5, scale=1), nullable=True),
    sa.Column('anschlussleistung_watt', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('einschaltstrom_faktor', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('shutdown_delay_seconds', sa.Integer(), nullable=True),
    sa.Column('shutdown_priority', sa.Integer(), nullable=True),
    sa.Column('shutdown_method', sa.Enum('ACPI_Graceful', 'SSH_Script', 'Hard_Power_Cut_PDU'), nullable=True),
    sa.Column('bemerkung', sa.String(length=255), nullable=True),
    sa.Column('inventarnummer', sa.String(length=100), nullable=True),
    sa.Column('geaendert_von', sa.String(length=100), nullable=True),
    sa.Column('geaendert_am', sa.DateTime(), nullable=True),
    sa.Column('strom_typ', sa.Enum('1-phasig', '3-phasig'), nullable=True),
    sa.Column('spannung_v', sa.Integer(), nullable=True),
    sa.Column('absicherung_a', sa.DECIMAL(precision=5, scale=1), nullable=True),
    sa.Column('anschluss_stecker', sa.Enum('CEE-16A-3P', 'CEE-32A-3P', 'CEE-63A-3P', 'C14', 'C20', 'Schuko', 'sonstige'), nullable=True),
    sa.Column('redundancy_path', sa.Enum('A', 'B'), nullable=True),
    sa.Column('min_rack_hoehe', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subnet_id'], ['subnets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname')
    )
    op.create_table('distribution_panels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bezeichnung', sa.String(length=100), nullable=False),
    sa.Column('rack_id', sa.Integer(), nullable=True),
    sa.Column('usv_unit_id', sa.Integer(), nullable=True),
    sa.Column('bemerkung', sa.String(length=255), nullable=True),
    sa.Column('has_epo_contact', sa.Boolean(), nullable=False),
    sa.Column('redundancy_path', sa.Enum('A', 'B'), nullable=True),
    sa.Column('geaendert_von', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usv_unit_id'], ['usv_units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usv_calculations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('berechnet_am', sa.DateTime(), nullable=False),
    sa.Column('usv_unit_id', sa.Integer(), nullable=False),
    sa.Column('last_kw', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('peak_kw', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('installiert_kw', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('reserve_kw', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('n1_kw', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('kaltstart_ok', sa.Boolean(), nullable=False),
    sa.Column('bemerkung', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['usv_unit_id'], ['usv_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usv_modules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usv_unit_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('leistung_kw', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.Enum('aktiv', 'reserve', 'defekt'), nullable=False),
    sa.Column('seriennummer', sa.String(length=100), nullable=True),
    sa.Column('geaendert_von', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['usv_unit_id'], ['usv_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usv_simulation_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('usv_unit_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usv_unit_id'], ['usv_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kabel_nr', sa.String(length=50), nullable=True),
    sa.Column('typ', sa.Enum('Cat6', 'Cat6A', 'Cat7', 'DAC', 'LC-LC', 'SC-SC', 'SFP+', 'Strom-C13', 'Strom-C19', 'Strom-Schuko', 'Strom-CEE-16A-3P', 'Strom-CEE-32A-3P', 'Strom-CEE-63A-3P', 'sonstige'), nullable=False),
    sa.Column('laenge_m', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('farbe', sa.String(length=30), nullable=True),
    sa.Column('von_device_id', sa.Integer(), nullable=True),
    sa.Column('von_port', sa.String(length=50), nullable=True),
    sa.Column('nach_device_id', sa.Integer(), nullable=True),
    sa.Column('nach_port', sa.String(length=50), nullable=True),
    sa.Column('verlegt_am', sa.Date(), nullable=True),
    sa.Column('verlegt_von', sa.String(length=100), nullable=True),
    sa.Column('bemerkung', sa.String(length=255), nullable=True),
    sa.Column('geaendert_von', sa.String(length=100), nullable=True),
    sa.Column('geaendert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nach_device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['von_device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kabel_nr')
    )
    op.create_table('device_dependencies',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_device_id', sa.Integer(), nullable=False),
    sa.Column('dependency_type', sa.String(length=50), nullable=True),
    sa.Column('dependency_group', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['depends_on_device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id', 'depends_on_device_id')
    )
    op.create_table('distribution_circuits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('bezeichnung', sa.String(length=50), nullable=False),
    sa.Column('phase', sa.Enum('L1', 'L2', 'L3'), nullable=False),
    sa.Column('absicherung_a', sa.DECIMAL(precision=5, scale=1), nullable=False),
    sa.Column('max_watt', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['panel_id'], ['distribution_panels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pdu_outlets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pdu_id', sa.Integer(), nullable=False),
    sa.Column('outlet_name', sa.String(length=50), nullable=False),
    sa.Column('phase', sa.Enum('L1', 'L2', 'L3'), nullable=True),
    sa.Column('steckdosentyp', sa.Enum('C13', 'C19', 'C14', 'C20', 'Schuko', 'CEE-16A'), nullable=True),
    sa.Column('max_watt', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('schaltbar', sa.Boolean(), nullable=False),
    sa.Column('redundancy_path', sa.Enum('A', 'B'), nullable=True),
    sa.Column('connected_device_id', sa.Integer(), nullable=True),
    sa.Column('connected_port', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['connected_device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pdu_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('virtual_machines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('host_device_id', sa.Integer(), nullable=True),
    sa.Column('hypervisor_typ', sa.Enum('vmware', 'hyper-v', 'kvm', 'xcpng', 'sonstige'), nullable=True),
    sa.Column('vm_id_extern', sa.String(length=50), nullable=True),
    sa.Column('betriebssystem', sa.String(length=100), nullable=True),
    sa.Column('dienst', sa.String(length=255), nullable=True),
    sa.Column('ip_adresse', sa.String(length=45), nullable=True),
    sa.Column('ipv6_adresse', sa.String(length=45), nullable=True),
    sa.Column('depends_on_vm_id', sa.Integer(), nullable=True),
    sa.Column('shutdown_priority', sa.Integer(), nullable=True),
    sa.Column('responsible', sa.String(length=100), nullable=True),
    sa.Column('subnet_id', sa.Integer(), nullable=True),
    sa.Column('bemerkung', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['depends_on_vm_id'], ['virtual_machines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['host_device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subnet_id'], ['subnets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interfaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('port_name', sa.String(length=50), nullable=False),
    sa.Column('typ', sa.String(length=50), nullable=False),
    sa.Column('mac_adresse', sa.String(length=17), nullable=True),
    sa.Column('status', sa.Enum('frei', 'belegt', 'defekt'), nullable=False),
    sa.Column('kabel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kabel_id'], ['cables.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runbook_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('runbook_id', sa.Integer(), nullable=False),
    sa.Column('layer_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('vm_id', sa.Integer(), nullable=True),
    sa.Column('freitext', sa.String(length=255), nullable=True),
    sa.Column('delay_seconds', sa.Integer(), nullable=False),
    sa.Column('responsible', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['layer_id'], ['runbook_layers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['runbook_id'], ['runbooks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vm_id'], ['virtual_machines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cable_strands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cable_id', sa.Integer(), nullable=False),
    sa.Column('strand_number', sa.Integer(), nullable=False),
    sa.Column('farbe', sa.String(length=30), nullable=True),
    sa.Column('von_port_id', sa.Integer(), nullable=True),
    sa.Column('nach_port_id', sa.Integer(), nullable=True),
    sa.Column('bemerkung', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cable_id'], ['cables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nach_port_id'], ['interfaces.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['von_port_id'], ['interfaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runbook_execution_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('runbook_device_id', sa.Integer(), nullable=False),
    sa.Column('abgehakt_am', sa.DateTime(), nullable=True),
    sa.Column('abgehakt_von', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['runbook_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['runbook_device_id'], ['runbook_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runbook_execution_steps')
    op.drop_table('cable_strands')
    op.drop_table('runbook_devices')
    op.drop_table('interfaces')
    op.drop_table('virtual_machines')
    op.drop_table('pdu_outlets')
    op.drop_table('distribution_circuits')
    op.drop_table('device_dependencies')
    op.drop_table('cables')
    op.drop_table('usv_simulation_events')
    op.drop_table('usv_modules')
    op.drop_table('usv_calculations')
    op.drop_table('distribution_panels')
    op.drop_table('devices')
    op.drop_table('usv_units')
    op.drop_table('subnets')
    op.drop_table('runbook_layers')
    op.drop_table('runbook_executions')
    op.drop_table('vlans')
    op.drop_table('runbooks')
    op.drop_table('racks')
    # ### end Alembic commands ###
