"""add last_pct to devices

Revision ID: d02c996b4cfd
Revises: 44396c87d2a5
Create Date: 2026-05-25 01:34:54.293036

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d02c996b4cfd"
down_revision: Union[str, Sequence[str], None] = "44396c87d2a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devices",
        sa.Column("last_pct", sa.DECIMAL(precision=5, scale=1), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("devices", "last_pct")
    # ### end Alembic commands ###
