"""add redundancy_path to pdu_outlets and devices, add min_rack_hoehe and absicherung_a to devices

Revision ID: fb9b7245773e
Revises: 916cf0460469
Create Date: 2026-06-09 12:20:29.945405

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "fb9b7245773e"
down_revision: Union[str, Sequence[str], None] = "916cf0460469"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devices",
        sa.Column("absicherung_a", sa.DECIMAL(precision=5, scale=1), nullable=True),
    )
    op.add_column(
        "devices", sa.Column("redundancy_path", sa.Enum("A", "B"), nullable=True)
    )
    op.add_column("devices", sa.Column("min_rack_hoehe", sa.Integer(), nullable=True))
    op.alter_column(
        "devices",
        "anschluss_stecker",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=50),
        type_=sa.Enum(
            "CEE-16A-3P", "CEE-32A-3P", "CEE-63A-3P", "C14", "C20", "Schuko", "sonstige"
        ),
        existing_nullable=True,
    )
    op.drop_column("devices", "anschlussleistung_a")
    op.add_column(
        "pdu_outlets", sa.Column("redundancy_path", sa.Enum("A", "B"), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pdu_outlets", "redundancy_path")
    op.add_column(
        "devices",
        sa.Column(
            "anschlussleistung_a", mysql.DECIMAL(precision=5, scale=1), nullable=True
        ),
    )
    op.alter_column(
        "devices",
        "anschluss_stecker",
        existing_type=sa.Enum(
            "CEE-16A-3P", "CEE-32A-3P", "CEE-63A-3P", "C14", "C20", "Schuko", "sonstige"
        ),
        type_=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=50),
        existing_nullable=True,
    )
    op.drop_column("devices", "min_rack_hoehe")
    op.drop_column("devices", "redundancy_path")
    op.drop_column("devices", "absicherung_a")
    # ### end Alembic commands ###
